Update build dep **Go**
Latest Go 1.11 not working

```sh
src/options.go:463:9: undefined: strings.ReplaceAll
note: module requires Go 1.13make: *** [Makefile:122: target/fzf-linux_amd64] Erro 2
```

(cherry picked from commit fc968f4af0cba627d97a57954a758dd8c694c0dc)